const {
  Client, GatewayIntentBits, EmbedBuilder, Events,
  ActionRowBuilder, ButtonBuilder, ButtonStyle,
} = require('discord.js');
const {
  joinVoiceChannel, createAudioPlayer, createAudioResource,
  AudioPlayerStatus, VoiceConnectionStatus, entersState, StreamType,
} = require('@discordjs/voice');
const { exec, spawn } = require('child_process');
const { promisify } = require('util');
const fs = require('fs');
const path = require('path');
const https = require('https');
const http = require('http');
const puppeteer = require('puppeteer-core');

const execAsync = promisify(exec);

const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildVoiceStates,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent,
  ],
});

const PREFIX = '.';
const guilds = new Map();
const searchSessions = new Map(); // userId → { results, index }

// ── Helpers ───────────────────────────────────────────────────────────────────
function extractVideoId(url) {
  const m = url.match(/(?:v=|youtu\.be\/|shorts\/)([a-zA-Z0-9_-]{11})/);
  return m?.[1] ?? null;
}

function isTikTokUrl(url) {
  return /tiktok\.com/i.test(url);
}

function fmtDuration(sec) {
  if (!sec) return 'Live';
  const h = Math.floor(sec / 3600), m = Math.floor((sec % 3600) / 60), s = Math.floor(sec % 60);
  return h
    ? `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`
    : `${m}:${String(s).padStart(2, '0')}`;
}

function fmtViews(n) {
  if (!n) return 'Unknown';
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return n.toString();
}

function sanitize(name) {
  return name.replace(/[/\\?%*:|"<>]/g, '-').trim();
}

function searchEmbed(results, index) {
  const r = results[index];
  return new EmbedBuilder()
    .setTitle(r.title)
    .setURL(r.url)
    .setColor(0xff0000)
    .setThumbnail(r.thumbnails?.[r.thumbnails.length - 1]?.url ?? null)
    .addFields(
      { name: 'Channel',  value: r.channel?.name ?? 'Unknown', inline: true },
      { name: 'Duration', value: fmtDuration(r.durationInSec),  inline: true },
      { name: 'Views',    value: fmtViews(r.views),              inline: true },
    )
    .setFooter({ text: `Result ${index + 1} of ${results.length} • .dl to download • .play to stream` });
}

function searchButtons(index, total) {
  return new ActionRowBuilder().addComponents(
    new ButtonBuilder().setCustomId('prev')    .setLabel('◀ Prev')      .setStyle(ButtonStyle.Secondary).setDisabled(index === 0),
    new ButtonBuilder().setCustomId('next')    .setLabel('Next ▶')      .setStyle(ButtonStyle.Secondary).setDisabled(index === total - 1),
    new ButtonBuilder().setCustomId('download').setLabel('⬇ Download')  .setStyle(ButtonStyle.Success),
    new ButtonBuilder().setCustomId('playBtn') .setLabel('▶ Play')      .setStyle(ButtonStyle.Primary),
  );
}


// ── phptools.org downloader via headless Chromium ─────────────────────────────
// Calling phptools.org as a plain HTTP API doesn't work — the public_url it
// returns is generated by client-side JavaScript after the page loads, so a
// raw HTTP request only ever gets the empty HTML shell back. Instead, we drive
// a real (headless) Chromium browser to do exactly what a person does manually:
// open the page, paste the link, click Download, and read the result.

function findChromiumPath() {
  const candidates = [
    process.env.PUPPETEER_EXECUTABLE_PATH,
    '/usr/bin/chromium',
    '/usr/bin/chromium-browser',
    '/usr/bin/google-chrome',
    '/usr/bin/google-chrome-stable',
  ].filter(Boolean);
  for (const p of candidates) { if (fs.existsSync(p)) return p; }
  return null;
}

async function launchBrowser() {
  const execPath = findChromiumPath();
  if (!execPath) throw new Error('Chromium is not installed in this container — check the Dockerfile');
  return puppeteer.launch({
    executablePath: execPath,
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
  });
}

async function phptoolsGetPublicUrl(videoUrl, onProgress) {
  const browser = await launchBrowser();

  try {
    const page = await browser.newPage();
    await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36');
    await page.goto('https://www.phptools.org/youtube/index.php', { waitUntil: 'domcontentloaded', timeout: 30000 });

    await page.waitForSelector('input[name="yt_url"]', { timeout: 15000 });
    await page.type('input[name="yt_url"]', videoUrl, { delay: 10 });

    // Click the main "Download" button. This can trigger a page navigation,
    // which destroys the current JS execution context — that's expected, so
    // we swallow that specific error rather than letting it bubble up.
    try {
      await page.evaluate(() => {
        const btns = Array.from(document.querySelectorAll('button'));
        const btn = btns.find(b => b.textContent.trim().toLowerCase() === 'download');
        if (btn) btn.click();
      });
    } catch (e) {
      if (!/context was destroyed|navigation/i.test(e.message)) throw e;
    }

    // Give any navigation triggered by the click a moment to settle.
    await page.waitForNavigation({ waitUntil: 'domcontentloaded', timeout: 8000 }).catch(() => {});

    const maxWaitMs = 150000;
    const start = Date.now();
    let publicUrl = null;

    while (Date.now() - start < maxWaitMs) {
      let text = null;
      try {
        text = await page.evaluate(() => document.body.innerText);
      } catch {
        // Page navigated again mid-read — just retry next loop iteration.
        await new Promise(r => setTimeout(r, 1500));
        continue;
      }
      const m = text.match(/"public_url"\s*:\s*"([^"]+)"/);
      if (m) { publicUrl = m[1]; break; }
      if (/error/i.test(text) && !/Too many stored videos/i.test(text)) {
        const errMatch = text.match(/"error"\s*:\s*"([^"]+)"/);
        if (errMatch) throw new Error(errMatch[1]);
      }
      await new Promise(r => setTimeout(r, 2000));
    }

    if (!publicUrl) throw new Error('Timed out waiting for the download to finish processing');
    return publicUrl.startsWith('http') ? publicUrl : ('https://phptools.org' + publicUrl);
  } finally {
    await browser.close();
  }
}

// ── TikTok downloader via snaptik.app (same browser-automation approach) ──────
async function tiktokGetDownloadUrl(videoUrl) {
  const browser = await launchBrowser();

  try {
    const page = await browser.newPage();
    await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36');
    await page.goto('https://downr.org/', { waitUntil: 'domcontentloaded', timeout: 30000 });

    const inputSelector = await page.evaluate(() => {
      const candidates = ['#url', 'input[name="url"]', 'input[type="text"]', 'input[type="url"]'];
      for (const sel of candidates) { if (document.querySelector(sel)) return sel; }
      return null;
    });
    if (!inputSelector) {
      const html = await page.content();
      console.error('[tiktok] no input field found, page html snippet:', html.slice(0, 1000));
      throw new Error('Could not find the URL input field on downr.org');
    }

    await page.click(inputSelector, { clickCount: 3 }).catch(() => {});
    await page.type(inputSelector, videoUrl, { delay: 10 });

    try {
      await page.evaluate(() => {
        const els = Array.from(document.querySelectorAll('button, input[type="submit"], a'));
        const btn = els.find(b => /download|search|go|submit/i.test(b.textContent || b.value || ''));
        if (btn) btn.click();
      });
    } catch (e) {
      if (!/context was destroyed|navigation/i.test(e.message)) throw e;
    }

    // Give the page time to process via AJAX, or settle after navigation.
    await page.waitForNavigation({ waitUntil: 'domcontentloaded', timeout: 6000 }).catch(() => {});
    await new Promise(r => setTimeout(r, 4000));

    const candidates = await page.evaluate(() => {
      const fromAnchors = Array.from(document.querySelectorAll('a')).map(a => ({
        tag: 'a', href: a.href, text: (a.textContent || '').trim(), cls: a.className || '',
      }));
      const fromVideos = Array.from(document.querySelectorAll('video, video source')).map(v => ({
        tag: 'video', href: v.src || v.currentSrc || '', text: '', cls: v.className || '',
      }));
      return [...fromAnchors, ...fromVideos].filter(a => a.href && a.href.startsWith('http'));
    });
    console.log('[tiktok] candidate links:', JSON.stringify(candidates).slice(0, 2000));

    const isJunk = l => /thumb|cover|preview|poster|avatar|icon|logo|favicon/i.test(l.href) || /thumb|cover|preview|poster/i.test(l.text);

    let dlUrl =
      candidates.find(l => !isJunk(l) && /without watermark|no watermark/i.test(l.text))?.href ??
      candidates.find(l => !isJunk(l) && /download/i.test(l.text) && /hd|high quality/i.test(l.text))?.href ??
      candidates.find(l => !isJunk(l) && /download/i.test(l.text) && /\.mp4(\?|$)/i.test(l.href))?.href ??
      candidates.find(l => !isJunk(l) && l.tag === 'video')?.href ??
      candidates.find(l => !isJunk(l) && /download/i.test(l.text))?.href ??
      candidates.find(l => !isJunk(l) && /\.mp4(\?|$)/i.test(l.href))?.href ??
      null;

    if (!dlUrl) {
      const debugText = await page.evaluate(() => document.body.innerText).catch(() => '');
      console.error('[tiktok] no download link found, page text:', debugText.slice(0, 800));
      throw new Error('Could not find a download link on downr.org');
    }
    console.log('[tiktok] selected link:', dlUrl.slice(0, 200));
    return dlUrl;
  } finally {
    await browser.close();
  }
}

async function ytInfo(url) {
  if (isTikTokUrl(url)) {
    return {
      title:     'TikTok Video',
      url,
      duration:  0,
      author:    'Unknown',
      thumbnail: null,
    };
  }
  const videoId = extractVideoId(url);
  if (!videoId) throw new Error('Invalid YouTube URL');
  return {
    title:     `Video ${videoId}`,
    url:       `https://www.youtube.com/watch?v=${videoId}`,
    duration:  0, // unknown until downloaded — phptools.org doesn't expose metadata via API
    author:    'Unknown',
    thumbnail: `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
  };
}

async function downloadMp4(url, outputPath, onProgress) {
  const dlUrl = isTikTokUrl(url)
    ? await tiktokGetDownloadUrl(url)
    : await phptoolsGetPublicUrl(url, onProgress);
  await streamToFile(dlUrl, outputPath);
  const sizeKB = fs.statSync(outputPath).size / 1024;
  console.log(`[download] saved ${sizeKB.toFixed(0)} KB from ${dlUrl.slice(0, 80)}`);
}

async function downloadMp3(url, outputPath, onProgress) {
  const dlUrl = isTikTokUrl(url)
    ? await tiktokGetDownloadUrl(url)
    : await phptoolsGetPublicUrl(url, onProgress);
  const tmp = outputPath + '_tmp.mp4';
  try {
    await streamToFile(dlUrl, tmp);
    await execAsync(`ffmpeg -i "${tmp}" -vn -ar 44100 -ac 2 -b:a 192k "${outputPath}" -y`);
  } finally {
    try { fs.unlinkSync(tmp); } catch {}
  }
}

async function getAudioResource(url) {
  const dlUrl = isTikTokUrl(url)
    ? await tiktokGetDownloadUrl(url)
    : await phptoolsGetPublicUrl(url);
  const ffmpeg = spawn('ffmpeg', [
    '-reconnect', '1', '-reconnect_streamed', '1', '-reconnect_delay_max', '5',
    '-i', dlUrl, '-vn', '-ar', '48000', '-ac', '2', '-f', 's16le', 'pipe:1',
  ], { stdio: ['ignore', 'pipe', 'ignore'] });
  return createAudioResource(ffmpeg.stdout, { inputType: StreamType.Raw });
}

function streamToFile(url, dest) {
  return new Promise((resolve, reject) => {
    const proto = url.startsWith('https') ? https : http;
    const file = fs.createWriteStream(dest);
    proto.get(url, res => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        file.close(); fs.unlink(dest, () => {});
        return streamToFile(res.headers.location, dest).then(resolve).catch(reject);
      }
      if (res.statusCode !== 200) { file.close(); return reject(new Error(`HTTP ${res.statusCode}`)); }
      res.pipe(file);
      file.on('finish', () => { file.close(); resolve(); });
    }).on('error', err => { fs.unlink(dest, () => {}); reject(err); });
  });
}

// ── yt-dlp (search only — RapidAPI has no search endpoint) ────────────────────
const YTDLP_BASE = ['--no-playlist', '--extractor-args', 'youtube:player_client=android', '--no-warnings', '--quiet'];

function ytdlpRun(args, timeoutMs = 30000) {
  return new Promise((resolve, reject) => {
    const proc = spawn('yt-dlp', args);
    let out = '', err = '';
    const timer = setTimeout(() => { proc.kill('SIGKILL'); reject(new Error('Search timed out')); }, timeoutMs);
    proc.stdout.on('data', d => out += d);
    proc.stderr.on('data', d => err += d);
    proc.on('close', code => {
      clearTimeout(timer);
      if (code === 0) return resolve(out);
      reject(new Error('Search failed — try .dl with a direct YouTube link instead'));
    });
  });
}

async function ytSearch(query, limit = 10) {
  const out = await ytdlpRun([`ytsearch${limit}:${query}`, '--dump-json', '--flat-playlist', ...YTDLP_BASE]);
  return out.trim().split('\n').filter(Boolean).map(line => {
    const v = JSON.parse(line);
    return {
      title:         v.title ?? 'Unknown',
      url:           `https://www.youtube.com/watch?v=${v.id}`,
      durationInSec: v.duration ?? 0,
      views:         v.view_count ?? 0,
      channel:       { name: v.channel || v.uploader || 'Unknown' },
      thumbnails:    [{ url: v.thumbnail || `https://i.ytimg.com/vi/${v.id}/hqdefault.jpg` }],
    };
  });
}

// ── Guild state ───────────────────────────────────────────────────────────────
function getGuild(guildId) {
  if (!guilds.has(guildId)) {
    const player = createAudioPlayer();
    const state = { queue: [], player, connection: null, current: null, textChannel: null };

    player.on(AudioPlayerStatus.Idle, async () => {
      state.current = null;
      if (state.queue.length > 0) await startPlaying(state);
      else if (state.textChannel) state.textChannel.send('✅ Queue finished!');
    });

    player.on('error', err => {
      console.error('Player error:', err.message);
      state.current = null;
      if (state.queue.length > 0) startPlaying(state);
    });

    guilds.set(guildId, state);
  }
  return guilds.get(guildId);
}

async function startPlaying(state) {
  if (!state.queue.length || !state.connection) return;
  const track = state.queue.shift();
  state.current = track;
  try {
    const resource = await getAudioResource(track.url);
    state.player.play(resource);
    if (state.textChannel) {
      state.textChannel.send({ embeds: [
        new EmbedBuilder()
          .setTitle('🎵 Now Playing')
          .setDescription(`[${track.title}](${track.url})`)
          .setColor(0xff0000)
          .addFields(
            { name: 'Duration', value: fmtDuration(track.duration), inline: true },
            { name: 'Channel',  value: track.author ?? 'Unknown',    inline: true },
          )
          .setThumbnail(track.thumbnail ?? null),
      ]});
    }
  } catch (err) {
    console.error('Stream error:', err.message);
    if (state.textChannel) state.textChannel.send(`❌ Couldn't play **${track.title}**, skipping...`);
    if (state.queue.length > 0) await startPlaying(state);
  }
}

async function ensureVoice(message, state) {
  const vc = message.member?.voice?.channel;
  if (!vc) { await message.reply('❌ Join a voice channel first!'); return false; }
  state.textChannel = message.channel;
  if (!state.connection || state.connection.state.status === VoiceConnectionStatus.Destroyed) {
    state.connection = joinVoiceChannel({
      channelId: vc.id,
      guildId: message.guild.id,
      adapterCreator: message.guild.voiceAdapterCreator,
    });
    state.connection.on(VoiceConnectionStatus.Disconnected, async () => {
      try {
        await Promise.race([
          entersState(state.connection, VoiceConnectionStatus.Signalling, 5_000),
          entersState(state.connection, VoiceConnectionStatus.Connecting, 5_000),
        ]);
      } catch { state.connection.destroy(); state.connection = null; }
    });
    state.connection.subscribe(state.player);
  }
  return true;
}

// ── Resolve a track from URL or search query ──────────────────────────────────
async function resolveTrack(query) {
  if (query.includes('youtube.com') || query.includes('youtu.be') || isTikTokUrl(query)) {
    return ytInfo(query);
  }
  const results = await ytSearch(query, 1);
  if (!results.length) throw new Error('No results found.');
  const r = results[0];
  return { title: r.title, url: r.url, duration: r.durationInSec, author: r.channel?.name, thumbnail: r.thumbnails?.[0]?.url };
}

// ── Download helper (shared by .dl command and ⬇ button) ─────────────────────
async function handleDownload(track, replyFn, sendFileFn) {
  if (track.duration > 600) {
    await replyFn('❌ Video is over 10 minutes. Use `.play` to stream it instead.');
    return;
  }
  const tmpDir = path.join('/tmp', `dl_${Date.now()}`);
  try {
    fs.mkdirSync(tmpDir, { recursive: true });
    const outputPath = path.join(tmpDir, `${sanitize(track.title)}.mp4`);
    await replyFn(`⏬ Downloading **${track.title}**...`);
    await downloadMp4(track.url, outputPath, msg => replyFn(msg));
    const sizeMB = fs.statSync(outputPath).size / (1024 * 1024);
    if (sizeMB > 25) {
      await replyFn(`❌ File is ${sizeMB.toFixed(1)} MB — too large for Discord. Try \`.play\` to stream it.`);
      return;
    }
    await replyFn(`✅ Sending **${track.title}** (${sizeMB.toFixed(1)} MB)...`);
    await sendFileFn(outputPath, `${sanitize(track.title)}.mp4`);
  } finally {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  }
}

// ── Commands ──────────────────────────────────────────────────────────────────
const commands = {};

// .yt — browse search results
commands.yt = async (message, args) => {
  if (!args.length) return message.reply('❌ Provide a search query. e.g. `.yt never gonna give you up`');
  const status = await message.reply('🔍 Searching YouTube...');
  try {
    const results = await ytSearch(args.join(' '), 10);
    if (!results.length) return status.edit('❌ No results found.');
    searchSessions.set(message.author.id, { results, index: 0 });
    await status.edit({ content: '', embeds: [searchEmbed(results, 0)], components: [searchButtons(0, results.length)] });
  } catch (err) {
    await status.edit(`❌ Search failed: \`${err.message}\``);
  }
};

// .dl — download current search result (or a direct URL/query)
commands.dl = async (message, args) => {
  let track;

  if (args.length) {
    const status = await message.reply('⏳ Fetching info...');
    try {
      track = await resolveTrack(args.join(' '));
      let statusText = '';
      await handleDownload(
        track,
        text => { statusText = text; return status.edit(text); },
        (filePath, name) => message.channel.send({ files: [{ attachment: filePath, name }] }),
      );
      if (statusText.startsWith('✅')) await status.delete().catch(() => {});
    } catch (err) {
      await status.edit(`❌ Error: \`${err.message}\``);
    }
    return;
  }

  const session = searchSessions.get(message.author.id);
  if (!session) return message.reply('❌ No active search. Use `.yt <query>` first, then browse with the buttons.');
  const r = session.results[session.index];
  track = { title: r.title, url: r.url, duration: r.durationInSec, author: r.channel?.name };

  const status = await message.reply(`⏳ Starting download...`);
  try {
    let statusText = '';
    await handleDownload(
      track,
      text => { statusText = text; return status.edit(text); },
      (filePath, name) => message.channel.send({ files: [{ attachment: filePath, name }] }),
    );
    if (statusText.startsWith('✅')) await status.delete().catch(() => {});
  } catch (err) {
    await status.edit(`❌ Error: \`${err.message}\``);
  }
};

// .mp3 — download as audio
commands.mp3 = async (message, args) => {
  let url;

  if (args.length) {
    try { url = (await resolveTrack(args.join(' '))).url; }
    catch (err) { return message.reply(`❌ ${err.message}`); }
  } else {
    const session = searchSessions.get(message.author.id);
    if (!session) return message.reply('❌ Provide a URL/query or use `.yt` first.');
    url = session.results[session.index].url;
  }

  const status = await message.reply('⏳ Fetching info...');
  const tmpDir = path.join('/tmp', `mp3_${Date.now()}`);
  try {
    const v = await ytInfo(url);
    if (v.duration > 1200) return status.edit('❌ Track is over 20 minutes — too long.');
    fs.mkdirSync(tmpDir, { recursive: true });
    const outputPath = path.join(tmpDir, `${sanitize(v.title)}.mp3`);
    await status.edit(`⏬ Downloading audio for **${v.title}**...`);
    await downloadMp3(url, outputPath, msg => status.edit(msg).catch(() => {}));
    const sizeMB = fs.statSync(outputPath).size / (1024 * 1024);
    if (sizeMB > 25) return status.edit(`❌ File is ${sizeMB.toFixed(1)} MB — too large.`);
    await status.edit(`✅ Sending **${v.title}** (${sizeMB.toFixed(1)} MB)...`);
    await message.channel.send({ files: [{ attachment: outputPath, name: `${sanitize(v.title)}.mp3` }] });
    await status.delete().catch(() => {});
  } catch (err) {
    await status.edit(`❌ Error: \`${err.message}\``);
  } finally {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  }
};

// .play — stream to voice
commands.play = async (message, args) => {
  const state = getGuild(message.guild.id);
  if (!await ensureVoice(message, state)) return;

  let track;
  if (!args.length) {
    const session = searchSessions.get(message.author.id);
    if (!session) return message.reply('❌ Provide a URL/query or use `.yt` to search first.');
    const r = session.results[session.index];
    track = { title: r.title, url: r.url, duration: r.durationInSec, author: r.channel?.name, thumbnail: r.thumbnails?.[r.thumbnails.length - 1]?.url };
  } else {
    const status = await message.reply('🔍 Searching...');
    try {
      track = await resolveTrack(args.join(' '));
      await status.delete().catch(() => {});
    } catch (err) {
      return status.edit(`❌ ${err.message}`);
    }
  }

  state.queue.push(track);
  if (state.player.state.status === AudioPlayerStatus.Idle) {
    await startPlaying(state);
  } else {
    await message.reply({ embeds: [
      new EmbedBuilder()
        .setTitle('➕ Added to Queue')
        .setDescription(`[${track.title}](${track.url})`)
        .setColor(0x00bfff)
        .addFields(
          { name: 'Position', value: `#${state.queue.length}`, inline: true },
          { name: 'Duration', value: fmtDuration(track.duration),  inline: true },
        )
        .setThumbnail(track.thumbnail ?? null),
    ]});
  }
};

commands.skip = async (message) => {
  const state = getGuild(message.guild.id);
  if (state.player.state.status === AudioPlayerStatus.Idle) return message.reply('❌ Nothing is playing.');
  state.player.stop();
  await message.reply('⏭️ Skipped!');
};

commands.queue = async (message) => {
  const state = getGuild(message.guild.id);
  if (!state.current && !state.queue.length) return message.reply('📭 The queue is empty.');
  const embed = new EmbedBuilder().setTitle('🎵 Queue').setColor(0xff0000);
  if (state.current) embed.addFields({ name: '▶️ Now Playing', value: `[${state.current.title}](${state.current.url}) | \`${fmtDuration(state.current.duration)}\``, inline: false });
  state.queue.slice(0, 9).forEach((t, i) => embed.addFields({ name: `${i + 1}. ${t.title}`, value: `[Link](${t.url}) | \`${fmtDuration(t.duration)}\``, inline: false }));
  if (state.queue.length > 9) embed.setFooter({ text: `…and ${state.queue.length - 9} more` });
  await message.reply({ embeds: [embed] });
};

commands.np = async (message) => {
  const state = getGuild(message.guild.id);
  if (!state.current) return message.reply('❌ Nothing is playing.');
  await message.reply({ embeds: [
    new EmbedBuilder()
      .setTitle('🎵 Now Playing')
      .setDescription(`[${state.current.title}](${state.current.url})`)
      .setColor(0xff0000)
      .addFields({ name: 'Duration', value: fmtDuration(state.current.duration), inline: true })
      .setThumbnail(state.current.thumbnail ?? null),
  ]});
};

commands.pause = async (message) => {
  const state = getGuild(message.guild.id);
  if (state.player.state.status !== AudioPlayerStatus.Playing) return message.reply('❌ Nothing is playing.');
  state.player.pause();
  await message.reply('⏸️ Paused.');
};

commands.resume = async (message) => {
  const state = getGuild(message.guild.id);
  if (state.player.state.status !== AudioPlayerStatus.Paused) return message.reply('❌ Nothing is paused.');
  state.player.unpause();
  await message.reply('▶️ Resumed.');
};

commands.stop = async (message) => {
  const state = getGuild(message.guild.id);
  state.queue = []; state.player.stop(true); state.current = null;
  await message.reply('⏹️ Stopped and queue cleared.');
};

commands.leave = async (message) => {
  const state = getGuild(message.guild.id);
  if (!state.connection) return message.reply('❌ Not in a voice channel.');
  state.queue = []; state.player.stop(true); state.current = null;
  state.connection.destroy(); state.connection = null;
  await message.reply('👋 Disconnected.');
};

commands.help = async (message) => {
  await message.reply({ embeds: [
    new EmbedBuilder()
      .setTitle('📖 Commands')
      .setColor(0xff0000)
      .addFields(
        { name: '🔍 Search & Download', value: '`.yt <query>` — browse results with ◀ ▶ buttons\n`.dl` — download current result as MP4\n`.dl <url or query>` — download directly\n`.mp3 [url or query]` — download as MP3', inline: false },
        { name: '🎵 Music', value: '`.play [url or query]` — stream to voice (no args = use current `.yt` result)\n`.skip` `.pause` `.resume` `.stop` `.np` `.queue` `.leave`', inline: false },
      )
      .setFooter({ text: 'Prefix: .' }),
  ]});
};

const aliases = {
  p: 'play', q: 'queue', dc: 'leave', disconnect: 'leave',
  next: 'skip', sk: 'skip', download: 'dl', audio: 'mp3', nowplaying: 'np',
};

// ── Button interaction handler ────────────────────────────────────────────────
client.on(Events.InteractionCreate, async (interaction) => {
  if (!interaction.isButton()) return;

  const session = searchSessions.get(interaction.user.id);
  if (!session) {
    return interaction.reply({ content: '❌ Your search session expired. Run `.yt` again.', ephemeral: true });
  }

  const { results } = session;

  if (interaction.customId === 'prev') {
    if (session.index > 0) session.index--;
    return interaction.update({ embeds: [searchEmbed(results, session.index)], components: [searchButtons(session.index, results.length)] });
  }

  if (interaction.customId === 'next') {
    if (session.index < results.length - 1) session.index++;
    return interaction.update({ embeds: [searchEmbed(results, session.index)], components: [searchButtons(session.index, results.length)] });
  }

  if (interaction.customId === 'download') {
    await interaction.deferReply();
    const r = results[session.index];
    const track = { title: r.title, url: r.url, duration: r.durationInSec };
    try {
      await handleDownload(
        track,
        text => interaction.editReply(text),
        (filePath, name) => interaction.channel.send({ files: [{ attachment: filePath, name }] }),
      );
      await interaction.deleteReply().catch(() => {});
    } catch (err) {
      await interaction.editReply(`❌ Error: \`${err.message}\``);
    }
    return;
  }

  if (interaction.customId === 'playBtn') {
    const vc = interaction.member?.voice?.channel;
    if (!vc) return interaction.reply({ content: '❌ Join a voice channel first!', ephemeral: true });
    const r = results[session.index];
    const track = { title: r.title, url: r.url, duration: r.durationInSec, author: r.channel?.name, thumbnail: r.thumbnails?.[r.thumbnails.length - 1]?.url };
    const state = getGuild(interaction.guild.id);
    state.textChannel = interaction.channel;
    if (!state.connection || state.connection.state.status === VoiceConnectionStatus.Destroyed) {
      state.connection = joinVoiceChannel({ channelId: vc.id, guildId: interaction.guild.id, adapterCreator: interaction.guild.voiceAdapterCreator });
      state.connection.on(VoiceConnectionStatus.Disconnected, async () => {
        try { await Promise.race([entersState(state.connection, VoiceConnectionStatus.Signalling, 5_000), entersState(state.connection, VoiceConnectionStatus.Connecting, 5_000)]); }
        catch { state.connection.destroy(); state.connection = null; }
      });
      state.connection.subscribe(state.player);
    }
    state.queue.push(track);
    if (state.player.state.status === AudioPlayerStatus.Idle) {
      await interaction.reply({ content: '▶️ Starting...', ephemeral: true });
      await startPlaying(state);
    } else {
      await interaction.reply({ content: `➕ Added **${track.title}** to queue at #${state.queue.length}`, ephemeral: true });
    }
  }
});

// ── Message handler ───────────────────────────────────────────────────────────
client.on(Events.MessageCreate, async (message) => {
  if (message.author.bot || !message.guild || !message.content.startsWith(PREFIX)) return;
  const [rawCmd, ...args] = message.content.slice(PREFIX.length).trim().split(/\s+/);
  const cmd = aliases[rawCmd.toLowerCase()] ?? rawCmd.toLowerCase();
  if (!commands[cmd]) return;
  try { await commands[cmd](message, args); }
  catch (err) {
    console.error(`[${cmd}] error:`, err);
    message.reply(`❌ Unexpected error: \`${err.message}\``).catch(() => {});
  }
});

client.once(Events.ClientReady, () => {
  console.log(`✅ Online as ${client.user.tag}`);
  client.user.setActivity('bren is cool', { type: 2 });
});

client.login(process.env.DISCORD_TOKEN);
